// Shared realistic demo therapist profiles for template preview pages

export const demoProfiles: Record<string, any> = {
  classic1: {
    id: 'demo-classic1',
    name: 'Dr. Nisha',
    credentials: 'PhD Clinical Psychology, RCI Licensed',
    bio: 'I work with adults navigating anxiety, burnout, grief, and the quieter struggles that rarely have simple names. My approach is warm, direct, and grounded in evidence — shaped by CBT, ACT, and somatic work.',
    image: '/template1.png',
    location: 'Mumbai, Maharashtra',
    experience: 10,
    fee: 1800,
    specialties: ['Anxiety & Panic', 'Burnout & Exhaustion', 'Grief & Loss', 'Self-Esteem', 'Life Transitions', 'Trauma Recovery'],
    languages: ['English', 'Hindi', 'Marathi'],
    sessionDuration: 50,
    sessionMode: 'both',
    phone: '',
    plan: 'pro',
    whatsapp: '',
    instagram: '',
    linkedin: '',
    website: '',
    tagline: 'Evidence-based care for the modern mind.',
    approach_text: 'I draw from CBT, ACT, and somatic practices to create therapy that is tailored, collaborative, and deeply human.',
    education: [
      { degree: 'PhD Clinical Psychology', institution: 'NIMHANS, Bangalore', year: '2014' },
      { degree: 'MA Applied Psychology', institution: 'University of Mumbai', year: '2011' },
    ],
    certifications: ['RCI Licensed Psychologist', 'EMDR Level II Certified', 'Mindfulness-Based Stress Reduction (MBSR)'],
    availability: null,
    profile_content: {},
  },
  classic2: {
    id: 'demo-classic2',
    name: 'Vikram Nair',
    credentials: 'MSc Psychotherapy, Certified Trauma Specialist',
    bio: 'Working with adults navigating life transitions, identity, and the complexity of modern relationships. My practice is rooted in depth psychology and relational work.',
    image: '/template2.png',
    location: 'Kochi, Kerala',
    experience: 9,
    fee: 1500,
    specialties: ['Life Transitions', 'Identity & Self', 'Relationships', 'CBT', 'ACT', 'Somatic Work'],
    languages: ['English', 'Malayalam', 'Hindi'],
    sessionDuration: 50,
    sessionMode: 'online',
    phone: '',
    plan: 'pro',
    whatsapp: '',
    instagram: '',
    linkedin: '',
    website: '',
    tagline: 'Depth psychology for a complex world.',
    approach_text: 'Integrating relational psychotherapy with CBT and ACT — meeting you where you are.',
    education: [
      { degree: 'MSc Psychotherapy', institution: 'Christ University, Bangalore', year: '2015' },
      { degree: 'BA Psychology', institution: 'Loyola College, Chennai', year: '2013' },
    ],
    certifications: ['CBT Certified Practitioner', 'ACT Level II', 'Somatic Experiencing Foundation'],
    availability: null,
    profile_content: {},
  },
  classic3: {
    id: 'demo-classic3',
    name: 'Kiran Singh',
    credentials: 'MSc Clinical Psychology, RCI Registered',
    bio: 'A practice rooted in compassion and evidence-based methods. I work with individuals and couple navigating anxiety, relationship difficulties, and trauma. Sessions are collaborative, warm, and tailored to your journey.',
    image: '/template3.png',
    location: 'Delhi, NCR',
    experience: 7,
    fee: 1200,
    specialties: ['Anxiety', 'Trauma & PTSD', 'Relationships', 'Couple Therapy', 'Depression', 'Mindfulness'],
    languages: ['English', 'Hindi'],
    sessionDuration: 50,
    sessionMode: 'both',
    phone: '',
    plan: 'pro',
    whatsapp: '',
    instagram: '',
    linkedin: '',
    website: '',
    tagline: 'Grounded. Safe. Hopeful.',
    approach_text: 'Integrating CBT, mindfulness, and relational approaches to create therapy that is safe and genuinely transformative.',
    education: [
      { degree: 'MSc Clinical Psychology', institution: 'Amity University, Delhi', year: '2017' },
      { degree: 'BSc Psychology', institution: 'Delhi University', year: '2015' },
    ],
    certifications: ['RCI Registered Psychologist', 'Gottman Method Couple Therapy Level I', 'Trauma-Focused CBT'],
    availability: null,
    profile_content: {
      classic3: {
        services: [
          { name: 'Individual Therapy', desc: 'One-to-one sessions for anxiety, depression, and personal growth.', price: 1200, kind: 'Individual', forWhom: ['Anxiety', 'Depression', 'Growth'] },
          { name: 'Couple Counselling', desc: 'Structured sessions to improve communication and rebuild connection.', price: 1800, kind: 'Couple', forWhom: ['Communication', 'Conflict', 'Intimacy'] },
          { name: 'Trauma Processing', desc: 'Trauma-informed care using EMDR and somatic techniques.', price: 1400, kind: 'Trauma', forWhom: ['PTSD', 'EMDR', 'Recovery'] },
        ],
        faqs: [
          { q: 'How long are sessions?', a: 'Each session is 50 minutes. We typically meet weekly, though frequency can be adjusted to suit your schedule.' },
          { q: 'Do you offer online sessions?', a: 'Yes — I offer both in-person sessions in Delhi and secure video sessions across India and internationally.' },
          { q: 'How many sessions will I need?', a: 'This varies. Some clients work through specific issues in 8-12 sessions; others prefer ongoing support. We always work at your pace.' },
        ],
        insights: [
          { title: 'Understanding Anxiety in the Body', excerpt: 'Why anxiety lives in the nervous system, and what that means for treatment.', category: 'Anxiety', date: 'March 2025' },
          { title: 'The Difference Between Grief and Depression', excerpt: 'Two experiences that can look similar but require very different support.', category: 'Grief', date: 'January 2025' },
          { title: 'Secure Attachment in Adult Relationships', excerpt: 'How early attachment patterns show up in our closest relationships and how to change them.', category: 'Relationships', date: 'November 2024' },
        ],
      }
    },
  },
  classic4: {
    id: 'demo-classic4',
    name: 'Dr. Millie Joseph',
    credentials: 'PhD Psychology, Certified Trauma Specialist, EMDR Practitioner',
    bio: 'Specialist trauma care delivered with precision and warmth. I work with individuals who have experienced complex trauma, PTSD, and the psychological aftermath of adverse experiences.',
    image: '/template4.png',
    location: 'New Delhi',
    experience: 14,
    fee: 2500,
    specialties: ['Complex Trauma', 'PTSD', 'EMDR', 'Dissociation', 'Personality Disorders', 'Military & First Responders'],
    languages: ['English', 'Hindi'],
    sessionDuration: 60,
    sessionMode: 'both',
    phone: '',
    plan: 'pro',
    whatsapp: '',
    instagram: '',
    linkedin: '',
    website: '',
    tagline: 'Precision trauma care. Deeply human.',
    approach_text: 'Integrating EMDR, somatic experiencing, and schema therapy to address trauma at every level.',
    education: [
      { degree: 'PhD Clinical Psychology', institution: 'IIT Delhi', year: '2010' },
      { degree: 'MSc Psychology', institution: 'University of Delhi', year: '2007' },
    ],
    certifications: ['EMDR Europe Certified', 'Somatic Experiencing Practitioner', 'Schema Therapy Level II', 'RCI Licensed'],
    availability: null,
    profile_content: {},
  },
  classic5: {
    id: 'demo-classic5',
    name: 'Karan Singh',
    credentials: 'MSc Clinical Psychology, RCI Registered',
    bio: 'A grounded, compassionate practice for those navigating anxiety, trauma, and the complexities of modern life. I bring warmth, evidence, and genuine curiosity to every session.',
    image: '/template5.png',
    location: 'Mumbai, Maharashtra',
    experience: 6,
    fee: 1100,
    specialties: ['Anxiety Relief', 'Burnout Recovery', 'Trauma Healing', 'Relationship Therapy', 'Life Transitions', 'Depression'],
    languages: ['English', 'Hindi', 'Marathi'],
    sessionDuration: 50,
    sessionMode: 'both',
    phone: '',
    plan: 'pro',
    whatsapp: '',
    instagram: '',
    linkedin: '',
    website: '',
    tagline: 'Where healing begins with honesty.',
    approach_text: 'Integrating mindfulness, CBT, and relational therapy to meet you exactly where you are.',
    education: [
      { degree: 'MSc Clinical Psychology', institution: 'TISS, Mumbai', year: '2019' },
      { degree: 'BSc Psychology', institution: 'University of Mumbai', year: '2017' },
    ],
    certifications: ['RCI Registered', 'Mindfulness-Based Cognitive Therapy (MBCT)', 'Trauma-Sensitive Yoga'],
    availability: null,
    profile_content: {
      classic5: {
        services: [
          { name: 'Individual Therapy', desc: 'Personalised one-to-one sessions for adults navigating anxiety, depression, or life challenges.', price: 1100, tag: 'Most Popular' },
          { name: 'Trauma Recovery', desc: 'Trauma-informed care using somatic and mindfulness-based approaches at your pace.', price: 1300, tag: 'Specialist' },
          { name: 'Relationship Counselling', desc: 'Support for individuals navigating relationship difficulties, attachment, and intimacy.', price: 1100, tag: '' },
          { name: 'Burnout & Stress', desc: 'Targeted support for professionals experiencing exhaustion, overwhelm, and loss of meaning.', price: 1100, tag: '' },
        ],
      }
    },
  },
  classic6: {
    id: 'demo-classic6',
    name: 'Dr. Aanya Mehta',
    credentials: 'M.Phil Clinical Psychology · RCI Licensed',
    bio: "I'm a licensed clinical psychologist. People usually find their way here at a point where something has quietly become too heavy to carry alone.\nMy work is unhurried and collaborative — less about fixing you, more about helping you understand yourself with a little more compassion and a lot less judgement.",
    image: '/template1.png',
    location: 'Bengaluru, Karnataka',
    experience: 12,
    fee: 1800,
    specialties: ['Anxiety & Stress', 'Relationships', 'Trauma & EMDR', 'Grief', 'Self-Esteem', 'Life Transitions'],
    languages: ['English', 'Hindi', 'Kannada'],
    sessionDuration: 50,
    sessionMode: 'both',
    phone: '',
    plan: 'pro',
    whatsapp: '',
    instagram: '',
    linkedin: '',
    website: '',
    tagline: "Therapy that doesn't rush you. A calm, confidential space to think clearly, feel fully, and move at your own pace.",
    approach_text: 'No pressure, no performance — just two people, working honestly, one session at a time.',
    education: [
      { degree: 'M.Phil Clinical Psychology', institution: 'NIMHANS, Bengaluru', year: '2012' },
      { degree: 'MA Psychology', institution: 'Christ University', year: '2009' },
    ],
    certifications: ['RCI Licensed Psychologist', 'EMDR Level II Certified', 'Certified in Trauma-Focused CBT'],
    availability: null,
    profile_content: {},
  },
}

export const demoBookedTimes: string[] = []

export const demoFeedbacks: any[] = [
  { id: '1', client_name: 'R.M.', client_role: 'Client', rating: 5, text: 'Six months later I have language for my feelings, tools for hard days, and a relationship with myself I never thought possible.', created_at: '2024-11-01' },
  { id: '2', client_name: 'S.K.', client_role: 'Client', rating: 5, text: 'Thoughtful, safe, and deeply effective. I finally feel like I have agency over my anxiety.', created_at: '2024-09-15' },
]
